Issues into develop
ripple214/trendsafe-safety-bff pull request #5
Opened 2021-11-12 16:09 UTC by Shrutika-GA

2021-11-12 21:56 UTC, ripple214 requested changes

2021-11-12 21:56 UTC, ripple214 commented on src/routes/assessments.router.ts
> +        (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date)? 1 : -1;
Date includes timestamps. It's very unlikely that b.completed_date will be equal to a.completed_date because of the varying minutes and seconds. If you're looking for same day, better change isAfter to isSameOrAfter

2021-11-12 21:56 UTC, ripple214 commented on src/routes/clients.router.ts
> -              } else if(access == 'TP') {
Please do not change the module id, as this is used internally in other processes as well. Changing this will require full site-wide testing.

2021-11-12 21:56 UTC, ripple214 commented on src/routes/hazards.router.ts
> +        return (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date) ? 1 : -1;
Same with first comment

2021-11-12 21:56 UTC, ripple214 commented on src/routes/inspections.router.ts
> +        return (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date) ? 1 : -1;
Same with first comment

2021-11-12 21:56 UTC, ripple214 commented on src/routes/managements.router.ts
> +        return (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date) ? 1 : -1;
Same with first comment

2021-11-12 21:56 UTC, ripple214 commented on src/routes/modules.router.ts
> +            } else if(module.id == 'PR') {
Same with second comment

2021-11-12 21:56 UTC, ripple214 commented on src/routes/plannings.router.ts
> +const moduleId = 'PR';
Unless you are able to perform full site-wide testing, please avoid changing moduleId

2021-11-15 17:24 UTC, Shrutika-GA commented on src/routes/assessments.router.ts
> +        (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date)? 1 : -1;
Tried that, was not getting expected output.

2021-11-15 18:01 UTC, ripple214 commented on src/routes/assessments.router.ts
> +        (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date)? 1 : -1;
If this is for sort order of in the listing page, main reason is because date string isn't being resolved correctly in linux. I'll investigate that.

2021-11-16 06:56 UTC, Shrutika-GA commented on src/routes/assessments.router.ts
> +        (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date)? 1 : -1;
Yes this is for sort order.

2021-11-16 07:11 UTC, Shrutika-GA commented on src/routes/clients.router.ts
> -              } else if(access == 'TP') {
changed back module id to TP

2021-11-16 08:39 UTC, ripple214 commented on src/routes/hazards.router.ts
> +        return (isAfter(b.completed_date, a.completed_date) || b.completed_date == a.completed_date) ? 1 : -1;
I've already transferred ownership of this repository to Jakob. Please ask him to accept the email notification and do not contact me again.

2021-11-16 09:28 UTC, merged